
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
run:
  concurrency: 10
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - example/
  skip-files:
    - Makefile
    - README.md
